package no.stelar7.kotmaw.riotconstant

enum class APIEndpoint
{
    SUMMONER_BY_NAME,
    SUMMONER_BY_ID,
    SUMMONER_BY_ACCOUNT,
    CHAMPION_MASTERY_ALL,
    MATCHLIST,
    MATCH_BY_ID,
    TIMELINE_BY_ID,
    THIRD_PARTY_CODE,
    LEAGUE_BY_SUMMONER,
    LEAGUE_BY_ID,
    LEAGUE_CHALLENGER,
    LEAGUE_MASTER,
    SPECTATOR_FEATURED,
    SPECTATOR_CURRENT
}

